export const rolePermissions = {
  SUPER_ADMIN: [], // all
  ADMIN: [
    'ADD_ROLE_PERMISSION',
    'REMOVE_ROLE_PERMISSION',
    'VIEW_ROLE_PERMISSION',
    'CREATE_DEVICE',
    'CREATE_HOUSE',
    'CREATE_AREA',
    'CREATE_RELATIONSHIP',
    'UPDATE_RELATIONSHIP',
    'DELETE_RELATIONSHIP',
    'CREATE_TYPE_DEVICE',
    'UPDATE_TYPE_DEVICE',
    'DELETE_TYPE_DEVICE',
    'CREATE_USER',
    'UPDATE_USER',
    'DELETE_USER',
    'UPDATE_CURRENT_USER',
    'AUTHORIZATION_PERMISSION_AREA',
    'AUTHORIZATION_PERMISSION_DEVICE',
    'AUTHORIZATION_PERMISSION_HOUSE',
    'AUTHORIZATION_PERMISSION_USER',
    'CREATE_GATEWAY',
    'UPDATE_GATEWAY',
    'DELETE_GATEWAY'
  ],
  CLIENT: []
}
